### ISSUE TITLE
Question about signal to noise

### ISSUE THREAD

**Issue by tuttlen** [DasLab/ubr#2]
My familiarity with MatLab is a little weak, however there is an issue with a method that is called and it doesn't exist.

It is the ubr_estimate_signal_to_noise_ratio which seems to be renamed to estimate_signal_to_noise_ratio.

Further, inspecting the following call:
      signal_to_noise(m,i) = ubr_estimate_signal_to_noise_ratio(r(m,good_seqpos,i)',r_err(m,good_seqpos,i)');

It appears that we are passing a single array to that function which treats it like an array to that function which then treats it like it has
a 2-dimensional array and means the values by the shape of the 2nd dimension. I am wondering if I am reading this wrong or if my 
understanding of matlab argument passing is errant.

**Comment by rhiju** [comment]
thanks for the question -- 
1. MATLAB  is forgiving about the `.m` file name being different from the function -- weirdly the `.m` file name takes precedence, which is why the code works. But it's confusing for us humans, so I just corrected it in 0d52fde6ea2b71414682601bc2ab78787ef36967. 
2. The function `ubr_estimate_signal_to_noise_ratio` was inherited from code elsewhere (in a package called MAPseeker, used for, e.g., th eKaggle OpenVaccine challenge.). The original function expects the first dimension to iterate along the sequence, and the second dimension (if provided) to iterate along different profiles. To use the same code here, note that the array `r(m,good_seqpos,i)'` passed in is transposed which, in MATLAB, is the `'` symbol, so all the dimensions work out. =)
